spring.application.name=pactime-multiplayer-api

spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration-days=7

security.google.client.id=${SECURITY_GOOGLE_CLIENT_ID}
security.google.client.secret=${SECURITY_GOOGLE_CLIENT_SECRET}
config.api.url=${CONFIG_API_URL}
