spring.application.name=pactime-multiplayer-api
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.open-in-view=true
spring.jpa.hibernate.ddl-auto=update

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-days=7

security.google.client-id=${GOOGLE_CLIENT_ID}
security.google.client-secret=${GOOGLE_CLIENT_SECRET}
config.api-url=${API_URL}
